{% set name = "verible" %}
{% set version = "0.0-3724-gdec56671" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/chipsalliance/verible/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 93f8b46a59fbf3731766565d479e0ca36791f908f8d3f46eede28266384bad68
  patches:
    - build_opts_patch.patch


build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - bazel >=5,<=7
    - bazel-toolchain
    - flex
    - bison
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - patchelf

test:
  commands:
    - verible-verilog-lint --version
    - verible-verilog-diff --version

about:
  home: https://github.com/chipsalliance/verible
  summary: |
    The Verible project's main mission is to parse SystemVerilog (IEEE 1800-2017)
    (as standardized in the SV-LRM) for a wide variety of applications, including 
    developer tools.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dillonroach
